---
- hosts: all
  gather_facts: false
  tasks:
    - name: install apache httpd
      yum: 
        name: "{{ item }}" 
        state: present
      with_items: 
        - httpd
        - httpd-devel  

    - name: Start the service of httpd
      service: name=httpd state=started


    - name: stop the service of httpd
      service: name=httpd state=reloaded
